"""empty message

Revision ID: 3431c65d6947
Revises: 6fa270ff91a1
Create Date: 2021-06-06 23:40:26.626236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3431c65d6947'
down_revision = '6fa270ff91a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('category')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    # ### end Alembic commands ###
